export const ADD_PROFILE = 'ADD_PROFILE'
export const DEL_PROFILE = 'DEL_PROFILE'

export const ADD_SUPERTOPICS = 'ADD_SUPERTOPICS'
export const DEL_SUPERTOPICS = 'DEL_SUPERSOPICS'

export const ADD_TOPICS = 'ADD_SUPERSOPICS'
export const DEL_TOPICS = 'DEL_SUPERSOPICS'

export const ADD_OVERALRAITING = 'ADD_OVERALRAITING'
export const DEL_OVERALRAITING = 'DEL_OVERALRAITING'

export const ADD_SCORES = 'ADD_SCORES'
export const DEL_SCORES = 'DEL_SCORES'